onlyBuiltDependencies:
  - '@sentry/cli'
  - 'sharp'
  - 'unrs-resolver'
packageManagerStrictVersion: true
publicHoistPattern:
  - '*eslint*'
  - '*@nextui-org/*'
  - '@t3-oss/*'
  - '@sentry/core'
  - '@wooorm/starry-night'
  # opentelemetry turbopack fix
  - 'import-in-the-middle'
  - 'require-in-the-middle'
savePrefix: ''
